### ISSUE TITLE
About the Final Velocity always sets to Zero

### ISSUE THREAD

**Issue by feiyuxiaoThu** [pflab-ut/jerk_optimal_velocity_planning#3]
For all the providing scenarios, in both Maximum Velocity Profil and Jerk Limit Profile , the end Speed all sets to Zero.

In sceneros like stop or ZeroMaximum, the settings are understandable; however, like norm or following the vehicle should not
stop in the whole task, so what's the reason of that ?

And can we easilly change this setting and use a constant velocity (not zero) instead?

Thanks again and Looking forward to your reply.

**Comment by purewater0901** [comment]
Since the trajectory length is bounded, we consider the vehicle should stop at the end of the trajectory in any scenarios. Howerver, if you want to change this setting you can change [these settings](https://github.com/pflab-ut/jerk_optimal_velocity_planning/blob/master/src/scenario_generator.cpp#L90).
